name: Build

on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'lollipop/**'
      - 'tiramisu/**'
      - 'gradle/**'
      - '*.gradle'
      - '*.properties'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: ${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Set environments
        run: |
          {
            echo "commit=$(echo ${{ github.sha }} | cut -c-7)"
            echo "repo=$(echo ${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/})"
          } >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew asD --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.repo }}@${{ env.commit }}
          path: |
            lollipop/build/outputs/apk/debug/lollipop-debug.apk
            tiramisu/build/outputs/apk/debug/tiramisu-debug.apk
